# Generated by Django 2.2 on 2022-02-01 18:48

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[api.validators.validate_positive], verbose_name='Номер')),
                ('date_of_delivery', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время поставки')),
                ('tonnage', models.PositiveIntegerField(validators=[api.validators.validate_positive], verbose_name='Тоннаж')),
                ('volume', models.PositiveIntegerField(validators=[api.validators.validate_positive], verbose_name='Объём')),
                ('density', models.FloatField(editable=False, verbose_name='Плотность')),
                ('shift_accepted', models.PositiveIntegerField(editable=False, verbose_name='Принявшая смена')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите фамилию сотрудника', max_length=200, verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Введите имя сотрудника', max_length=200, verbose_name='Имя')),
                ('third_name', models.CharField(help_text='Введите отчество сотрудника', max_length=200, verbose_name='Отчество')),
                ('date_of_employment', models.DateField(verbose_name='Дата устройства на работу')),
                ('date_of_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('gender', models.CharField(choices=[('MALE', 'мужской'), ('FEMALE', 'женский')], default='мужской', max_length=6, verbose_name='Пол')),
                ('experience', models.IntegerField(editable=False, verbose_name='Опыт')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование продукта')),
                ('current_volume', models.PositiveIntegerField(validators=[api.validators.validate_positive], verbose_name='Текущий объем')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование резервуара')),
                ('capacity', models.PositiveIntegerField(validators=[api.validators.validate_positive], verbose_name='Ёмкость')),
            ],
            options={
                'verbose_name': 'Резервуар',
                'verbose_name_plural': 'Резервуары',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_beginning', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала смены')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время конца смены')),
                ('begin_vol_of_prod', models.FloatField(editable=False, null=True, verbose_name='Объем продуктов на начало смены')),
                ('end_delta_vol_of_prod', models.FloatField(editable=False, null=True, verbose_name='Дельта объёмов продуктов на конец смены')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.Batch', verbose_name='Партия')),
                ('employees', models.ManyToManyField(related_name='employees', to='api.Employee', verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(validators=[api.validators.validate_positive], verbose_name='Объём')),
                ('date_of_delivery', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время продажи')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.Shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.Product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='batch',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.Provider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='batch',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.Reservoir', verbose_name='Резервуар'),
        ),
    ]
