# Generated by Django 2.2 on 2022-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='current_volume',
            field=models.FloatField(editable=False, null=True, verbose_name='Фактический объём продуктов у смены'),
        ),
    ]
